externalURL: https://harbor.sandbox.local

expose:
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-cert

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m

    hosts:
      core: harbor.${DOMAIN}
      notary: notary.${DOMAIN}

persistence:
  enabled: false
