initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.2
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
    - name: minio
      provider: aws
      bucket: backups
      default: true
      caCert: $(cat pki/ca.crt | base64 -w 0)
      credential:
        name: minio-creds
        key: creds

      config:
        region: minio
        s3ForcePathStyle: true
        s3Url: https://minio.sandbox.local

  volumeSnapshotLocation:
    - name: minio
      provider: aws
      config:
        region: minio

      credentials:
        name: minio-creds
        key: creds

deployNodeAgent: true