apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
  name: ${NAMESPACE}
---
apiVersion: v1
kind: Pod
metadata:
  name: minio
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: minio
spec:
  containers:
    - name: minio
      image: quay.io/minio/minio:latest
      args:
        - server
        - /data
        - --console-address
        - :9001
      ports:
        - containerPort: 9001
          name: console
        - containerPort: 9000
          name: api
      volumeMounts:
        - name: minio-storage
          mountPath: /data
        - name: timezone
          mountPath: /etc/timezone
          readOnly: true
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
  volumes:
    - name: minio-storage
      hostPath:
        path: /storage/minio
    - name: timezone
      hostPath:
        path: /etc/timezone
        type: File
    - name: localtime
      hostPath:
        path: /etc/localtime
        type: File
---
kind: Service
apiVersion: v1
metadata:
  name: minio
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
  type: ClusterIP
  ports:
    - name: console
      port: 9001
      targetPort: console
    - name: api
      port: 9000
      targetPort: api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: minio
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - minio-console.${DOMAIN}
        - minio-api.${DOMAIN}
      secretName: minio-cert
  rules:
    - host: minio-console.${DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: minio
                port:
                  name: console
    - host: minio-api.${DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: minio
                port:
                  name: api
